name: telemung
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  font_awesome_flutter: ^10.4.0
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  open_file: ^3.3.2
  pdf: ^3.10.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/